server:
  port: 8080

spring:
  application:
    name: book-review
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: admin
    password: example
    driverClassName: org.postgresql.Driver
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false