server:
  port: 8080

spring:
  application:
    name: book-review
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: admin
    password: example
    initialization-mode: always

jpa:
  show-sql: true
  hibernate:
    ddl-auto:
  properties:
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false