version: '3.8'
services: 
  prod:
    image: postgres:latest
    environment: 
      POSTGRES_DB: prod
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Pa$$w0rd
    ports:
      - "5433:5432"
    volumes:
      - app-volume:/var/lib/postgresql/data

  test:
    image: postgres:latest
    environment: 
      POSTGRES_DB: dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  

volumes:
  app-volume: #
